apiVersion: v1
kind: Service
metadata:
  name: octobroker
  labels:
    app.kubernetes.io/name: octobroker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: octobroker
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
