image:
  repository: ghcr.io/openabdev/openab
  tag: "0.10.0-beta.5"

agents:
  kiro:
    enabled: false

  caocao:
    enabled: true
    nameOverride: "caocao-codex"
    image: "ghcr.io/openabdev/openab-codex:latest"
    configUrl: "https://raw.githubusercontent.com/xfalcons/openab-config/refs/heads/main/guandu/config-caocao.toml"
    serviceAccountName: "openab"

  zhangliao:
    enabled: true
    nameOverride: "zhangliao-opencode"
    image: "ghcr.io/openabdev/openab-opencode:latest"
    configUrl: "https://raw.githubusercontent.com/xfalcons/openab-config/refs/heads/main/guandu/config-zhangliao.toml"
    serviceAccountName: "openab"